# Generated by Django 5.0.2 on 2024-02-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cad_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
